### ISSUE TITLE
demo的问题

### ISSUE THREAD

**Issue by xiawanyingtest** [soooban/AxonDemo#1]
1.问题
snapshot_event_entry表没有生成数据，是什么原因？

**Comment by jokefaker** [comment]
snapshot_event_entry 只会在生成快照的时候才会生成，demo 在 `AxonContinueConfiguration` 指定了每 5 个事件生成一次快照，你观察下是否是这样，如果还生成不了，那么可能是 aggregate 在序列化的时候报错了，导致没法存储。
