### ISSUE TITLE
查询问题

### ISSUE THREAD

**Issue by xiawanyingtest** [soooban/AxonDemo#2]
1.问题
1.如果我想通过最新的name或者其他条件查询，我该怎么做呢？
contract_view表里面的数据，是第一次保存的数据，不是最新的，更新时并没有更新这个表
我看代码有   // 2. 分发事件到各个 handler
这个逻辑，但是执行更新业务时，ContractEventHandler也没收到事件
2.能给个查询最新状态列表数据的例子吗？

**Comment by jokefaker** [comment]
最近比较忙，一直没关注 Github ...
```   
 @StreamEventHandler(types = ChannelDefinition.CONTRACTS_INPUT)
    public void handle(ContractCreatedEvent event, DomainEvent<ContractCreatedEvent, HashMap> domainEvent) {
        contractViewService.updateViewFromAggregateById(event.getIdentifier(), domainEvent.getTimestamp());
    }
```
1. 这里为了做 demo 只监听了 create 事件，update 时间只需要加一个监听 update 事件的方法，然后执行同样的逻辑即可；
2. 最新状态列表直接查询 contract_view 表即可，和传统的 Read 没有任何区别
