### ISSUE TITLE
DuplicateMappingException occurs on using of Spring boot 2.2.2.RELEASE and Spring cloud Hoxton.SR1

### ISSUE THREAD

**Issue by sharework-ai** [soooban/AxonDemo#3]
大神你好，不知道为何使用Spring boot 2.2.2.RELEASE和Spring cloud Hoxton.SR1后（请原谅我有使用最新依赖的强迫症），此项目无法启动了，报这个错误：

org.hibernate.DuplicateMappingException: The [org.axonframework.eventsourcing.eventstore.jpa.DomainEventEntry] and [com.craftsman.eventsourcing.es.continuance.producer.jpa.CustomDomainEventEntry] entities share the same JPA entity name: [DomainEventEntry] which is not allowed!

我知道CustomDomainEventEntry这个实体类，想要代替原本org.axonframework.eventsourcing.eventstore.jpa.DomainEventEntry，代码如下：

@Entity(name = "DomainEventEntry")
@Getter
@Setter
@Table(indexes = @Index(columnList = "aggregateIdentifier,sequenceNumber", unique = true))
@EntityListeners(CustomDomainEventEntryListener.class)
public class CustomDomainEventEntry extends AbstractSequencedDomainEventEntry<byte[]> {
}

@Configuration
@RegisterDefaultEntities(packages = {
    "org.axonframework.eventsourcing.eventstore.jpa"
})
public class AxonContinueConfiguration {
}

从代码的字面上理解，肯定会造成DuplicateMappingException，然而为何Spring boot 2.1.5.RELEASE（及Spring cloud Greenwich.SR1）不会，而升级之后就会呢？

我忽略了哪个细节了吗？如果想要使用最新的依赖，该怎么做？请指教，谢谢！

**Comment by sharework-cn** [comment]
Dear All,

    After copy SnapshotEventEntry from axon library to the project, and remove the @RegisterDefaultEntities, it had been solved for me.

Regards!

**Comment by sharework-ai** [comment]
Remove the @RegisterDefaultEntities annotation and add the orm.xml with following content in META-INF folder, the issue is solved.

```
<?xml version="1.0" encoding="UTF-8" ?>
<entity-mappings xmlns="http://java.sun.com/xml/ns/persistence/orm"
                 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                 xsi:schemaLocation="http://java.sun.com/xml/ns/persistence/orm http://java.sun.com/xml/ns/persistence/orm_2_0.xsd"
                 version="2.0">
    <entity class="org.axonframework.eventsourcing.eventstore.jpa.SnapshotEventEntry" access="FIELD">
        <attributes>
            <id name="aggregateIdentifier">
                <column name="aggregateIdentifier"/>
            </id>
            <id name="sequenceNumber">
                <column name="sequenceNumber"/>
            </id>
            <id name="type">
                <column name="type"/>
            </id>
        </attributes>
    </entity>
</entity-mappings>
```
